config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  root to: 'static_pages#root'

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post "comment"
      post "message"
      post "like"
      delete "unlike"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :books, only: [:show] do
    member do
      post "comment"
      post "like"
      delete "unlike"
    end
  end
  resources :collects, only: [:create]
  resources :comments, only: [:create, :update, :destroy]

  namespace :api, defaults: { format: :json } do
  	resources :books, only: [:index, :create, :show, :destroy, :update] do
      member do
        post "comment"
        post "like"
        delete "unlike"
      end
    end
    resources :users, only: [:show] do
      member do
        post "comment"
        post "like"
        post "message"
        delete "unlike"
      end
    end
    resources :authbooks, only: [:index]
  	resources :collections, except: [:new, :edit]
  	resources :collects, only: [:create, :destroy]
    resources :user_searches, only: [:index]
    resources :availbooks, only: [:index]
  end

  get "rankings", to: "static_pages#rankings"
  get "search", to: "searches#index"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/auth/email', to: 'sessions#email_required'
  post '/auth/email', to: 'sessions#save_email'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]

  include PgSearch
  after_initialize :ensure_session_token

  validates :session_token, :email, :password_digest, presence: true
  validates :session_token, :email, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  has_many(:authored_books,
           class_name: "Book",
           foreign_key: :author_id,
           primary_key: :id,
           inverse_of: :author
           )

  has_many :collections

  has_many(:comments,
           class_name: "Comment",
           foreign_key: :commenter_id,
           primary_key: :id,
           inverse_of: :commenter
           )
            
  has_many(:comments_on,
           class_name: "Comment",
           foreign_key: :commentable_id,
           primary_key: :id,
           as: :commentable
          )

  has_many(:received_messages,
           class_name: "Message",
           foreign_key: :to_id,
           primary_key: :id,
           inverse_of: :to
           )

  has_many(:sent_messages,
           class_name: "Message",
           foreign_key: :from_id,
           primary_key: :id,
           inverse_of: :from
           )

  has_many(:likings,
           class_name: "Like",
           foreign_key: :liker_id,
           primary_key: :id,
           inverse_of: :liker
           )

  has_many(:likes, 
           class_name: "Like",
           foreign_key: :likable_id,
           primary_key: :id,
           as: :likable
           )

  has_many :likers, through: :likes, source: :liker

  pg_search_scope :search_on_fname_lname, against: [:fname, :lname]

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    user && user.is_password?(password) ? user : nil
  end

  def self.find_or_create_by_auth_hash(auth_hash)
    where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create do |user|
      user.email = auth_hash.info.email
      user.password_digest = Devise.friendly_token[0, 20]
      full_name_arr =  auth_hash.info.name.split " "
      user.fname = full_name_arr.first
      user.lname = full_name_arr.last
    end
  end

  def self.create_by_auth_hash_and_email(email, auth_hash)
    where(provider: auth_hash[:provider], uid: auth_hash[:uid]).first_or_create do |user|
      user.email = email
      user.password_digest = Devise.friendly_token[0, 20]
      full_name_arr =  auth_hash[:name].split " "
      user.fname = full_name_arr.first
      user.lname = full_name_arr.last
    end
  end

  def likes?(user)
    liked = user.likers
    liked.include?(self)
  end

  def generate_token
    random_token = SecureRandom.base64(16)

    until self.session_token != random_token
      random_token = SecureRandom.base64(16)
    end

    random_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def ensure_session_token
    self.session_token ||= generate_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_token
    self.save!
    self.session_token
  end
end

app/controllers/api/users_controller.rb
module Api
	class UsersController < ApiController
		def show
			@user = User.find(params[:id])
			@books = @user.authored_books
			@comments = @user.comments_on

			render :show
		end

  	def comment
	    @user = User.find(params[:id])
	    @comment = @user.comments_on.new(comment_params)
	    @comment.commenter_id = current_user.id
	    if @comment.save
	      render json: {fname: current_user.fname}     
	    else
	      render json: @comment.errors.full_messages, status: 422
	    end
	  end

	  def message
	    @user = User.find(params[:id])
	    @message = @user.received_messages.new(message_params)
	    @message.from_id = current_user.id
	    if @message.save
	      render json: {fname: current_user.fname}    
	    else
	      render json: @message.errors.full_messages, status: 422
	    end
	  end

	  def like
	    @user = User.find(params[:id])
	    @like = @user.likes.new(liker_id: current_user.id)
	    if @like.save
	      render json: @like
	    else
	      render json: @like.errors.full_messages, status: 422
	    end
	  end

	  def unlike
	    @user = User.find(params[:id])
	    if current_user.likes?(@user)
	      @like = @user.likes.find_by(liker_id: current_user.id)
	      @like.destroy
	      render json: {}
	    else
	    	render json: "Cannot unlike this user.", status: 422
	    end
	  end

	private

		def comment_params
	      params.require(:comment).permit(:body)
	    end

	    def message_params 
	      params.require(:message).permit(:body)
	    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.find_or_create_by_auth_hash(auth_hash)
		if @user.persisted?
			login! @user
			redirect_to root_url
		else
			cookies[:provider] = auth_hash[:provider]
			cookies[:uid] = auth_hash[:uid]
			cookies[:name] = auth_hash.info.name
			redirect_to auth_email_url
		end
	end

	def failure
		puts auth_hash
		redirect_to root_url
	end

	private
	def auth_hash
		request.env["omniauth.auth"]
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, only: [:edit, :comment, :message, :like]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Successfully created your account! Here's your library."
      login!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_url(@user)
  end

  def comment
    @user = User.find(params[:id])
    @comment = @user.comments_on.new(comment_params)
    @comment.commenter_id = current_user.id
    if @comment.save
      flash[:notice] = "Comment saved."     
    else
      flash[:notice] = "Cannot save comment."
    end
    redirect_to user_url(@user)
  end

  def message
    @user = User.find(params[:id])
    @message = @user.received_messages.new(message_params)
    @message.from_id = current_user.id
    if @message.save
      flash[:notice] = "Message sent."     
    else
      flash[:notice] = "Cannot send message."
    end
    redirect_to user_url(@user)
  end

  def like
    @user = User.find(params[:id])
    @like = @user.likes.new(liker_id: current_user.id)
    if @like.save
      flash[:notice] = "You have liked this profile."
    else
      flash[:notice] = "Cannot like this profile."
    end
    redirect_to user_url(@user)
  end

  def unlike
    @user = User.find(params[:id])
    if current_user.likes?(@user)
      @like = @user.likes.find_by(liker_id: current_user.id)
      flash[:notice] = "You have unliked this profile."
      @like.destroy
      redirect_to user_url(@user)
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :fname, :lname, :password)
    end

    def comment_params
      params.require(:comment).permit(:body)
    end

    def message_params 
      params.require(:message).permit(:body)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<section class="login-form">
<% if user.persisted? %>
  <h1>Edit Profile</h1>
<% else %>
  <h1>User Signup</h1>
<% end %>
<form action="<%= user.persisted? ? user_url(user) : users_url %>" method="POST">
  <%= csrf_token %>
  <label>Email (required)
    <input type="text" name="user[email]" value="<%= user.email %>">
  </label>
  <label>First Name
	<input type="text" name="user[fname]" value="<%= user.fname %>">
  </label>
  <label>Last Name
	<input type="text" name="user[lname]" value="<%= user.lname %>">
  </label>
  <label>Password (required)
    <input type="password" name="user[password]" value="<% user.password %>">
  </label>
  <br>
  <% if user.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
    <button class="form-button">Update</button>
  <% else %>
    <button class="form-button">Sign up!</button>
  <% end %>
</form>
</section>

app/views/users/edit.html.erb
<%= render partial: "form", locals: { user: @user } %> 

app/views/users/new.html.erb
<section class="login-form">
<h1>User Signup</h1>

<form action="<%= users_url %>" method="POST">
  <%= csrf_token %>
  <label>Email
    <input type="text" name="user[email]">
  </label>
  <br>
  <label>Password
    <input type="password" name="user[password]">
  </label>
  <button class="form-button">Sign up!</button>
</form>
</section>

app/views/users/show.html.erb
<% if logged_in? %>
	<% if current_user.id == @user.id %>
		<h1>Hi, this is your profile</h1>
		<a href="<%= edit_user_url(@user) %>" class="text-link">Edit</a>
		<h2>Received messages</h2>
		<% unless @user.received_messages.empty? %>
		<ul class="search-results">
			<% @user.received_messages.each do |message| %>
				<li>
					<p>From: <%= message.from.fname || "Anonymous" %></p>
					<p><%= message.body %></p>
				</li>
			<% end %>
		</ul>
		<% else %>
			<p>You have not received any messages.</p>
		<% end %>
	<% else %>
		<% if current_user.likes?(@user) %>
			<form action="<%= unlike_user_url(@user) %>" method="POST">
				<%= csrf_token %>
				<input type="hidden" name="_method" value="DELETE">
				<button>Unlike</button>
			</form>
		<% else %>
			<form action="<%= like_user_url(@user) %>" method="POST">
				<%= csrf_token %>
				<button>Like</button>
			</form>
		<% end %>
	<% end %>
<% else %>
	<% if @user.fname == nil || @user.lname == nil %>
		<h1>Profile of Anonymous</h1>
	<% else %>
		<h1>Profile of <%= @user.fname + " " + @user.lname %></h1>
	<% end %>
<% end %>

<span class="like-stat">Likes: <%= @user.likes_count %></span>
<h2>Comments on this profile</h2>
<ul class="search-results">
	<% @user.comments_on.each do |comment| %>
		<li>
			<p>Commenter: <%= comment.commenter.fname || "Anonymous" %></p>
			<p>Body: 
				<br>
				<%= comment.body %>
			</p>
		</li>
	<% end %>
</ul>

<% if logged_in? %>
	<% unless current_user.id == @user.id %>
	<form action="<%= comment_user_url(@user) %>" method="POST">
		<%= csrf_token %>
		<label>Leave a comment
			<textarea name="comment[body]"></textarea>
		</label>
		<button>Post Comment</button>		
	</form>

	<form action="<%= message_user_url(@user) %>" method="POST">
		<%= csrf_token %>
		<label>Message this user
			<textarea name="message[body]"></textarea>
		</label>
		<button>Send Message</button>
	</form>
	<% end %>
<% end %>