config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  root to: 'static_pages#root'

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post "comment"
      post "message"
      post "like"
      delete "unlike"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :books, only: [:show] do
    member do
      post "comment"
      post "like"
      delete "unlike"
    end
  end
  resources :collects, only: [:create]
  resources :comments, only: [:create, :update, :destroy]

  namespace :api, defaults: { format: :json } do
  	resources :books, only: [:index, :create, :show, :destroy, :update] do
      member do
        post "comment"
        post "like"
        delete "unlike"
      end
    end
    resources :users, only: [:show] do
      member do
        post "comment"
        post "like"
        post "message"
        delete "unlike"
      end
    end
    resources :authbooks, only: [:index]
  	resources :collections, except: [:new, :edit]
  	resources :collects, only: [:create, :destroy]
    resources :user_searches, only: [:index]
    resources :availbooks, only: [:index]
  end

  get "rankings", to: "static_pages#rankings"
  get "search", to: "searches#index"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/auth/email', to: 'sessions#email_required'
  post '/auth/email', to: 'sessions#save_email'
end

app/models/book.rb
class Book < ActiveRecord::Base
  include PgSearch
  validates :author_id, :title, :genre, :synopsis, presence: true
  validates :genre, 
            inclusion: { in: %w(Misc Nonfiction Fiction Photobook Textbook Science) }
  has_attached_file :cover, default_url: "default.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
  has_attached_file :content, styles: { thumbnail: ["100x100#", :png] }, default_url: "/"
  validates_attachment :content, content_type: { content_type: "application/pdf" }

  belongs_to(:author,
            class_name: "User",
            foreign_key: :author_id,
            primary_key: :id,
            inverse_of: :authored_books
            )

  has_many :comments, as: :commentable
  has_many :likes, as: :likable
  has_many :likers, through: :likes, source: :liker

  pg_search_scope :search_on_title_synopsis, against: [:title, :synopsis]
  pg_search_scope :search_by_author_email, 
                  associated_against: { :author => :email },
                  using: { :tsearch => { :prefix => true }} 

  def liked_by?(user)
    likers = self.likers
    likers.include?(user)
  end

end

app/controllers/api/books_controller.rb
module Api
  class BooksController < ApiController
    skip_before_action :require_signed_in!, only: [:show, :index]
    wrap_parameters false

    def index
      if logged_in?
        @books = exclude_authored(current_user.id)
                     .page(params[:page])
                     .per(5)
      else
        @books = Book.includes(:author).page(params[:page]).per(5)
      end
      
      render :index
    end

    def comment
      @book = Book.find(params[:id])
      @comment = @book.comments.new(body: params[:body])
      @comment.commenter_id = current_user.id
      if @comment.save
        render json: {fname: current_user.fname}
      else
        render json: "Cannot save comment."
      end
    end

    def create
      @book = current_user.authored_books.new(book_params)
    
      if @book.save
        render json: @book
      else
        render json: @book.errors.full_messages, status: 422
      end
    end

    def show
      @book = Book.find(params[:id])
      @comments = @book.comments
      
      render :show
    end

    def destroy
      @book = Book.find(params[:id])
      
      if @book.author_id == current_user.id
        if @book.destroy
          render json: {}
        else
          render json: @book.errors.full_messages, status: 422
        end
      else
        render json: "You did not write this book."
      end
    end

    def update
      @book = Book.find(params[:id])

      if @book.author_id == current_user.id
        if @book.update(book_params)
          render json: @book
        else
          render json: @book.errors.full_messages, status: 422
        end
      end
    end

    def like
      @book = Book.find(params[:id])
      @like = @book.likes.new(liker_id: current_user.id)
      if @like.save
        render json: @like
      else
        render json: @like.errors.full_messages, status: 422
      end
    end

    def unlike
      @book = Book.find(params[:id])
      if @book.liked_by?(current_user)
        @like = @book.likes.find_by(liker_id: current_user.id)
        @like.destroy
        render json: {}
      end
    end

  private

    def book_params
      params.require(:book).permit(:title, :genre, :synopsis, :cover, :content)
    end

    def comment_params
      params.require(:comment).permit(:body)
    end

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :require_signed_in!, only: [:comment, :like, :unlike]
	def show
		@book = Book.find(params[:id])
		if logged_in?
			user_collections = current_user.collections
			@collections = user_collections.select { |collection| !collection.books.include?(@book) }
		end

		render :show		
	end

	def comment
		@book = Book.find(params[:id])
	    @comment = @book.comments.new(comment_params)
	    @comment.commenter_id = current_user.id
	    if @comment.save
	      redirect_to book_url(@book)
	    else
	      flash[:notice] = "Cannot save comment."
	      redirect_to book_url(@book)
	    end
	end

	def like
    @book = Book.find(params[:id])
    @like = @book.likes.new(liker_id: current_user.id)
    if @like.save
      flash[:notice] = "You have liked this book."
    else
      flash[:notice] = "Cannot like this book."
    end
    redirect_to book_url(@book)
  end

  def unlike
    @book = Book.find(params[:id])
    if @book.liked_by?(current_user)
      @like = @book.likes.find_by(liker_id: current_user.id)
      flash[:notice] = "You have unliked this book."
      @like.destroy
      redirect_to book_url(@book)
    end
  end

	private
		def comment_params
      		params.require(:comment).permit(:body)
    	end
end

app/views/books/show.html.erb
<h1>Title: <%= @book.title %><h1>
<h3 class="author-email">Author Email: <%= @book.author.email %></h3>
<article>
	<h3>Synopsis</h3><p><%= @book.synopsis %></p>
	<img src="<%= asset_path(@book.cover.url(:original)) %>" width="500">
		<% if asset_path(@book.content.url(:original)) != "/" %>
			<a href="<%= asset_path(@book.content.url(:original)) %>">
				<img src="<%= asset_path(@book.content.url(:thumbnail)) %>">
			</a>
		<% else %>
			<p>No pdf file uploaded</p>
		<% end %>
</article>
<% if logged_in? %>
	<% if @book.author.id == current_user.id %>
		<h3>You are the author of this book</h3>
	<% else %>
		<% if @book.liked_by?(current_user) %>
			<form action="<%= unlike_book_url(@book) %>" method="POST">
				<%= csrf_token %>
				<input type="hidden" name="_method" value="DELETE">
				<button>Unlike</button>
			</form>
		<% else %>
			<form action="<%= like_book_url(@book) %>" method="POST">
				<%= csrf_token %>
				<button>Like</button>
			</form>
		<% end %>
		<form action="<%= collects_url %>" method="POST">
			<%= csrf_token %>
			<input type="hidden" name="collect[book_id]" value="<%= @book.id %>">
			<strong class="form-label">Add to: </strong>
			<select name="collect[collection_id]">
				<% @collections.each do |collection| %>
					<option class="form-text" value="<%= collection.id %>"><%= collection.name %></option>
				<% end %>
			</select>
			<% if @collections.length > 0 %>
				<button class="select">Add to Collection</button>	
			<% else %>
				<p>All of your collections have this book... or maybe you have not created any collections.</p>
			<% end %>
		</form>
	<% end %>
<% end %>

<p>Likes: <%= @book.likes_count %></p>
<h2>Comments on this Book</h2>
<ul class="search-results">
	<% @book.comments.each do |comment| %>
		<li>
			<p>Commenter: <%= comment.commenter.fname || "Anonymous" %></p>
			<p>Body: 
				<br>
				<%= comment.body %>
			</p>
		</li>
	<% end %>
</ul>

<% if logged_in? %>
	<form action="<%= comment_book_url(@book) %>" method="POST">
		<%= csrf_token %>
		<label>Leave a comment
			<textarea name="comment[body]"></textarea>
		</label>
		<button>Post Comment</button>		
	</form>
<% end %>