config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  root to: 'static_pages#root'

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post "comment"
      post "message"
      post "like"
      delete "unlike"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :books, only: [:show] do
    member do
      post "comment"
      post "like"
      delete "unlike"
    end
  end
  resources :collects, only: [:create]
  resources :comments, only: [:create, :update, :destroy]

  namespace :api, defaults: { format: :json } do
  	resources :books, only: [:index, :create, :show, :destroy, :update] do
      member do
        post "comment"
        post "like"
        delete "unlike"
      end
    end
    resources :users, only: [:show] do
      member do
        post "comment"
        post "like"
        post "message"
        delete "unlike"
      end
    end
    resources :authbooks, only: [:index]
  	resources :collections, except: [:new, :edit]
  	resources :collects, only: [:create, :destroy]
    resources :user_searches, only: [:index]
    resources :availbooks, only: [:index]
  end

  get "rankings", to: "static_pages#rankings"
  get "search", to: "searches#index"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/auth/email', to: 'sessions#email_required'
  post '/auth/email', to: 'sessions#save_email'
end

app/views/layouts/_header.html.erb
<header class="group">
  <a href="<%= root_url %>" class="logo">Enwritt</a>
  <span id="magnifying-glass"></span>
  <form class="query-form group" method="GET" action="<%= search_url %>">
  <input type="text" name="query" class="search-box">
  <select name="search_by" id="search-option">Search By
    <option value="book" selected>Book</option>
    <option value="author">Author</option>
  </select>
  <button class="search-button">Search</button>
  </form>
  <% if logged_in? %>
    <h3 class="welcome-message"> Welcome <%= current_user.fname.blank? ? "Anonymous" : current_user.fname %> </h3>
    <form class="auth" method="POST" action="<%= session_url %>">
      <%= csrf_token %>
      <input type="hidden" name="_method" value="delete">
      <button class="sign-out">Sign out</button>
    </form>
    <a href="<%= user_url(current_user) %>" class="header-links">Profile</a>
  <% else %>
    <a href="<%= new_session_url %>" class="header-links">Sign in</a>
    <a href="<%= new_user_url %>" class="header-links">Sign up</a>
  <% end %>
  <a href="<%= rankings_url %>" class="header-links">Rankings</a>
</header>

app/views/layouts/_sidebar.html.erb
<section class="sidebar">
	<strong class="form-label">Top 10 Books</strong><br>
	<ol>
		<% book_rankings.each do |book| %>
			<li>
				<a class="sidebar-link" href="<%= book_url(book) %>"><%= book.title %></a>
			</li>
		<% end %>
	</ol>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enwritt</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <p class="error"><%= error %></p>
  <% end %>
<% end %>
<% unless logged_in? %>
<%= render "layouts/sidebar" %>
<% end %>
<%= yield %>

</body>
</html>